# Generated by Django 4.2 on 2024-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cistella',
            name='quantitat',
        ),
        migrations.RemoveField(
            model_name='cistella',
            name='producte',
        ),
        migrations.AddField(
            model_name='cistella',
            name='producte',
            field=models.ManyToManyField(to='shop.producte'),
        ),
    ]
